<?php namespace modules\server;

include_once('src/Status.inc');
include_once('src/Headers.inc');
include_once('src/Methods.inc');
include_once('src/Content.inc');
include_once('src/Response.inc');

use core\src\module\Module;
use core\src\module\ModuleInfo;
use modules\server\src\Content;
use modules\server\src\Headers;
use modules\server\src\Response;
use modules\server\src\Status;

#[
  ModuleInfo
  (
    author: 'Clay Whitelytning',
    version: '1.1.3',
    description: 'Simple non-configurable server'
  )
]
class Server extends Module
{
  /**
   * Contains a response generated by other modules.
   * @var Response
   */
  private Response $response;

  /**
   * Server initialization.
   * @return void
   */
  public function onModuleInit(): void
  {
    $this->response = new Response(new Status(Status::HTTP_NOT_FOUND), new Headers(), new Content());
  }

  /**
   * Unloading the server.
   * @return void
   */
  public function onModuleEnd(): void
  {
    http_response_code($this->response->getStatus()->getCode());
    if ($headers = $this->response->getHeaders()->toStrings()) {
      foreach ($headers as $header) header($header);
    }
    echo $this->response->getContent();
  }
}