<?php namespace engine\server;

include_once('includes/Status.inc');
include_once('includes/Headers.inc');
include_once('includes/Methods.inc');
include_once('includes/Content.inc');
include_once('includes/Response.inc');

use engine\includes\module\ModuleInfo;
use engine\includes\plugin\Plugin;
use engine\server\includes\Content;
use engine\server\includes\Headers;
use engine\server\includes\Response;
use engine\server\includes\Status;

#[
  ModuleInfo(
    name: 'Server',
    author: 'Clay Whitelytning',
    version: '1.1.2',
    description: 'Simple non-configurable server'
  )
]
class Server extends Plugin
{
  /**
   * Contains a response generated by other modules.
   * @var Response
   */
  private Response $response;

  /**
   * Server initialization.
   * @return void
   */
  public function onModuleInit(): void
  {
    $this->response = new Response(new Status(Status::HTTP_NOT_FOUND), new Headers(), new Content());
  }

  /**
   * Unloading the server.
   * @return void
   */
  public function onModuleEnd(): void
  {
    http_response_code($this->response->getStatus()->getCode());
    if ($headers = $this->response->getHeaders()->toStrings()) {
      foreach ($headers as $header) header($header);
    }
    echo $this->response->getContent();
  }
}