<?php namespace longhorn\server;

include_once('src/Status.inc');
include_once('src/Headers.inc');
include_once('src/Methods.inc');
include_once('src/Content.inc');
include_once('src/Response.inc');

use core\src\book\Book;
use longhorn\server\src\Content;
use longhorn\server\src\Headers;
use longhorn\server\src\Response;
use longhorn\server\src\Status;

/**
 * Class Server
 * @package longhorn\server
 */
class Server extends Book
{
  /**
   * Contains a response generated by other books.
   * @var Response
   */
  private Response $response;

  /**
   * Server initialization.
   * @return void
   */
  public function initialization(): void
  {
    $this->response = new Response(new Status(Status::HTTP_NOT_FOUND), new Headers(), new Content());
  }

  /**
   * Unloading the server.
   * @return void
   */
  public function finalization(): void
  {
    http_response_code($this->response->getStatus()->getCode());
    if ($headers = $this->response->getHeaders()->toStrings()) {
      foreach ($headers as $header) header($header);
    }
    echo $this->response->getContent();
  }
}