<?php namespace lib\longhorn\server;

include_once('src/Status.inc');
include_once('src/Headers.inc');
include_once('src/Methods.inc');
include_once('src/Content.inc');
include_once('src/Response.inc');

use core\src\book\Book;
use core\src\book\BookInfo;
use lib\longhorn\server\src\Content;
use lib\longhorn\server\src\Headers;
use lib\longhorn\server\src\Response;
use lib\longhorn\server\src\Status;

#[BookInfo('Clay Whitelytning', '1.1.3', 'Simple non-configurable server')]
class Server extends Book
{
  /**
   * Contains a response generated by other books.
   * @var Response
   */
  private Response $response;

  /**
   * Server initialization.
   * @return void
   */
  public function initialization(): void
  {
    $this->response = new Response(new Status(Status::HTTP_NOT_FOUND), new Headers(), new Content());
  }

  /**
   * Unloading the server.
   * @return void
   */
  public function finalization(): void
  {
    http_response_code($this->response->getStatus()->getCode());
    if ($headers = $this->response->getHeaders()->toStrings()) {
      foreach ($headers as $header) header($header);
    }
    echo $this->response->getContent();
  }
}